---
title: "Mapping Quandl Data"
output: html_notebook
---

  

```{r Import SF Object, message = FALSE, warning = FALSE}
library(rnaturalearth)
library(sf)
world <- ne_countries(type = "countries",  returnclass='sf')

# Take a peek at the name, gdp_md_est column and economy columns. 
head(world[c('name', 'gdp_md_est', 'economy')], n = 6)
```



```{r Build Map, message = FALSE, warning = FALSE}
library(leaflet)
##create shading by GDP
gdpPal <- colorQuantile("Purples", world$gdp_md_est, n = 20)

##create popup country name and economic stage
popup <- paste0("<strong>Country: </strong>", 
                world$name, 
                "<br><strong>Market Stage: </strong>", 
                world$income_grp)
```

 

```{r Leaflet Map Build, warning = FALSE, message = FALSE}

leaf_world <- leaflet(world) %>%
  addProviderTiles("CartoDB.Positron") %>% 
  setView(lng =  20, lat =  15, zoom = 2) %>%
      addPolygons(stroke = FALSE, smoothFactor = 0.2, fillOpacity = .7, 
      # Note the layer ID. Not a country name! It's a country code! 
      color = ~gdpPal(gdp_md_est), layerId = ~iso_a3, popup = popup)

leaf_world
```


```{r}
# Save
save(leaf_world, world, file = 'wdiMapData.RDat')
```


```{r China GDPPC, message = FALSE}
library(Quandl)
library(dplyr)
library(purrr)
China_GDPPC <- Quandl("WWDI/CHN_NY_GDP_PCAP_KN", type = 'xts') %>% 
  # Add a nice column name
  `colnames<-`("GDP Per Capita")

tail(China_GDPPC, n = 6)
```


```{r Many Econ Indicators}

# Create a vector of economic indicators that can be passed to Quandl via map().
# Include names and values for easy naming of xts columns.
econIndicators <- c("GDP Per Capita" = "WWDI/CHN_NY_GDP_PCAP_KN",
                  "GDP Per Capita Growth" = "WWDI/CHN_NY_GDP_PCAP_KD_ZG",
                  "Real Interest Rate" = "WWDI/CHN_FR_INR_RINR",
                  "Exchange Rate" = "WWDI/CHN_PX_REX_REER",
                  "CPI" = "WWDI/CHN_FP_CPI_TOTL_ZG",
                  "Labor Force Part. Rate" = "WWDI/CHN_SL_TLF_ACTI_ZS")
# You might want to supply an api key
Quandl.api_key("d9EidiiDWoFESfdk5nPy")

China_all_indicators <- 
  # Start with the vector of Quandl codes
  econIndicators %>% 
  # Pass them to Quandl via map(). 
  map(Quandl, type = "xts") %>% 
  # Use the reduce() function to combine them into one xts objects.
  reduce(merge) %>% 
  # Use the names from the original vector to set nicer column names.
  `colnames<-`(names(econIndicators))

tail(China_all_indicators, n = 6)
```

```{r}
# Include names and values for easy naming of xts columns.
econIndicators2 <- c("GDP Per Capita" = "_NY_GDP_PCAP_KN",
                  "GDP Per Capita Growth" = "_NY_GDP_PCAP_KD_ZG",
                  "Real Interest Rate" = "_FR_INR_RINR",
                  "Exchange Rate" = "_PX_REX_REER",
                  "CPI" = "_FP_CPI_TOTL_ZG",
                  "Labor Force Part. Rate" = "_SL_TLF_ACTI_ZS")
# You might want to supply an api key
Quandl.api_key("d9EidiiDWoFESfdk5nPy")
library(purrr)
China_all_indicators2 <- 
  # Start with the vector of Quandl codes
  econIndicators2 %>%
  map_chr(~paste("WWDI/", "CHN", ., sep="")) %>% 
  # Pass them to Quandl via map().
  map(Quandl, type = "xts") %>% 
  
  # Use the reduce() function to combine them into one xts objects.
  reduce(merge) %>% 
  # Use the names from the original vector to set nicer column names.
  `colnames<-`(names(econIndicators2))
tail(China_all_indicators2, n=6)
econIndicators
```



```{r Dygraph}
library(dygraphs)
dygraph(China_all_indicators$`GDP Per Capita`, main = "GDP Per Capita")
dygraph(China_all_indicators$`GDP Per Capita Growth`, main = "GDP Per Capita Growth")
dygraph(China_all_indicators$`Real Interest Rate`, main = "Real Interest Rate")
dygraph(China_all_indicators$`Exchange Rate`, main = "Exchange Rate")
dygraph(China_all_indicators$`CPI`, main = "CPI")
dygraph(China_all_indicators$`Labor Force Part. Rate`, main = "Labor Force Part. Rate")
```

```{r}
library(highcharter)
test_hc <- China_all_indicators2[,1]
hc <- highchart(type = "stock") %>% 
  hc_title(text = "Charting Econ Data From Quandl") %>% 
  hc_subtitle(text = "Data extracted using Quandl package") %>% 
  hc_add_series(China_all_indicators2[,2], name = names(China_all_indicators2[,2]), id = "test") %>% 
  hc_add_series(China_all_indicators2[,3], name = names(China_all_indicators2[,3]), id = "test1") 
hc
```
```